const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{Sólido: 0},
	{chao: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Piscar: 0},
	{play: 0},
	{Sprite: 0},
	{esquerda: 0},
	{direita: 0},
	{pulo: 0},
	{Toque: 0},
	{plataforma: 0},
	{Sprite2: 0},
	{caixa: 0},
	{portaEntrada: 0},
	{portaSaida: 0},
	{Limites: 0},
	{PartículasCaixa: 0},
	{Chave: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Senóide: 0},
	{inimogoh: 0},
	{Sprite6: 0},
	{botao: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{particulainimigo: 0},
	{Sprite9: 0},
	{tvtchaves: 0},
	{Sprite10: 0},
	{texvidas: 0},
	{Áudio: 0},
	{estado: 0},
	{achouChave: 0},
	{vidas: 0},
	{chaves: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	chao: class extends self.ITiledBackgroundInstance {},
	play: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	esquerda: class extends self.ISpriteInstance {},
	direita: class extends self.ISpriteInstance {},
	pulo: class extends self.ISpriteInstance {},
	Toque: class extends self.IInstance {},
	plataforma: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	caixa: class extends self.ISpriteInstance {},
	portaEntrada: class extends self.ISpriteInstance {},
	portaSaida: class extends self.ISpriteInstance {},
	Limites: class extends self.ISpriteInstance {},
	PartículasCaixa: class extends self.IParticlesInstance {},
	Chave: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	inimogoh: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	botao: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	particulainimigo: class extends self.IParticlesInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	tvtchaves: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	texvidas: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {}
}